apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-1
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium:
        policyEnforcementMode: default
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.80.8.129
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: mpaygude-mgmt
  gitOpsRef:
    kind: GitOpsConfig
    name: gitops
  kubernetesVersion: "1.24"
  managementCluster:
    name: mpaygude-mgmt
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  osImageURL: http://10.80.8.63:8000/ubuntu-123.gz
  tinkerbellIP: 10.80.8.130

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  hardwareSelector:
    type: worker
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDofFHTATsR3WikwckAzpqwbASiU2EAlT0NsIoYVMnsgQL5Dv6w9OiaWW6OUme40DA755ZjrhQmFcOHli4qh23W0BsVIrdSNl2FJkWASIyjBxIoYki8beRjI9g0JXWiEQl6uwornec8WKvrUmoYUNeKwAKYMMSgpMogMSPzq9GeGnSc7o/yyaVjKIH3Py1eGSLh7Qm+oCKPgYcYIk79VFn27ZhWyMukA8Y3FGJPbK8U9GZh5qkJ+WfX7wfrNb/q+pA7gQ/o0mpRyog3exVQDfWUgwanqEfl2NDkb93gTW87NPEww4jyT6CkS5smYGLI+8+26PMq0kmUg4FrzMA7Rx00qSPx5HZkRvBjmyp+9+KA8rApJRSQqIT3Gx+6PrLsoBptmECmsDi7yPoa5rsKKmEA1cGKpD7qnlAI3hTTLzbgxzrQuqZA6HYWMzfrSf967ExoZHMco+H76jFvd/3IcPwK0WldNgfYElj35xA5b8EsTXqmw7VlnI0wE8nRpdv7hBtD0lRRGf7mgW/OJkklYHg56UFbXcT8ZkIxnLWdcV7IVvlim7opeBeSB7Sronj7GMbuoRVVZcAF2mxRYuZxWK2aL78J2XTsp9y5/wSiJQ8EfsLtbU66ChSMKn/vo45FI0/BLvtmAbWAF0iWgpWHtutyHYviVOQZrBPi3uLNle0pkw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: mpaygude-mgmt-cp
  namespace: default
spec:
  hardwareSelector:
    type: cp
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDofFHTATsR3WikwckAzpqwbASiU2EAlT0NsIoYVMnsgQL5Dv6w9OiaWW6OUme40DA755ZjrhQmFcOHli4qh23W0BsVIrdSNl2FJkWASIyjBxIoYki8beRjI9g0JXWiEQl6uwornec8WKvrUmoYUNeKwAKYMMSgpMogMSPzq9GeGnSc7o/yyaVjKIH3Py1eGSLh7Qm+oCKPgYcYIk79VFn27ZhWyMukA8Y3FGJPbK8U9GZh5qkJ+WfX7wfrNb/q+pA7gQ/o0mpRyog3exVQDfWUgwanqEfl2NDkb93gTW87NPEww4jyT6CkS5smYGLI+8+26PMq0kmUg4FrzMA7Rx00qSPx5HZkRvBjmyp+9+KA8rApJRSQqIT3Gx+6PrLsoBptmECmsDi7yPoa5rsKKmEA1cGKpD7qnlAI3hTTLzbgxzrQuqZA6HYWMzfrSf967ExoZHMco+H76jFvd/3IcPwK0WldNgfYElj35xA5b8EsTXqmw7VlnI0wE8nRpdv7hBtD0lRRGf7mgW/OJkklYHg56UFbXcT8ZkIxnLWdcV7IVvlim7opeBeSB7Sronj7GMbuoRVVZcAF2mxRYuZxWK2aL78J2XTsp9y5/wSiJQ8EfsLtbU66ChSMKn/vo45FI0/BLvtmAbWAF0iWgpWHtutyHYviVOQZrBPi3uLNle0pkw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops
  namespace: default
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/mpaygude-mgmt
      fluxSystemNamespace: flux-system
      owner: mitalipaygude
      personal: true
      repository: gitops-tink

---
