apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-1
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium:
        policyEnforcementMode: default
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.80.9.129
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: mpaygude-mgmt
  gitOpsRef:
    kind: GitOpsConfig
    name: gitops
  kubernetesVersion: "1.24"
  managementCluster:
    name: mpaygude-mgmt
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  osImageURL: http://10.80.8.63:8000/ubuntu-123.gz
  tinkerbellIP: 10.80.9.130

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: mpaygude-mgmt-cp
  namespace: default
spec:
  hardwareSelector:
    type: cp
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5H1WpC5hhaYIQQoioKJyJf3iXABYVps4A1Wi8aLKcQZUKFscS+BcVim8hlIRc44l+1cz40hXVZqwKsbp6fbulkhdmaBWHyNA2QmKdqEvfNBv3Pu0tsg7QyaXnlvbn885457x/5fGAsFXNpPkw7doHaeqSueXcaQuEc2lSjx/a/iVdkYgFA86RBnMvbOmPVFg/8eI1vtEa9YJ/18MGYc+Yv2vFsnLasKNGIYmNTP73VlCXf/9R3zQE0sY850JcvDDJtHIM/PTVmIqaeILFgyvo6zJefjbKTaDp2S2yj+91gNgWhyahRMLshu1nQmUcbyvtnza2Jkh6SuFPQbST68LOUF874FUoLVA0uJtzxXWW++5NCoqE8/RbFVALCNE3BlDDjCYHJ68rnQEslU1u8hsdiPB9HkARWhrvOCRvdhPlRrunN4BC/jbnAdiNat9Pe9DoVkoPd8j7+gmjokgN8GH+I8NT9BOdcCKlG6vk/Dt6Yxxz9m3Rf918pDlm4/DK8UoXDCRbXyBjq++KjoFU6UpUOsONxGsV23deglFQeWxDZqBJ8w/Xh1hp5k2yo3CX+oXAREI021E+ogWx5+ismwg1pLDehhsyNkpcJidEwLF/OfI2/H3uGrzJhcYiV6YEFLhW3GTsKjyW8z4SqLttd/dIP8hTyxQmhG/KKO6CnciL5w==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  hardwareSelector:
    type: worker
  osFamily: ubuntu
  templateRef: {}
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5H1WpC5hhaYIQQoioKJyJf3iXABYVps4A1Wi8aLKcQZUKFscS+BcVim8hlIRc44l+1cz40hXVZqwKsbp6fbulkhdmaBWHyNA2QmKdqEvfNBv3Pu0tsg7QyaXnlvbn885457x/5fGAsFXNpPkw7doHaeqSueXcaQuEc2lSjx/a/iVdkYgFA86RBnMvbOmPVFg/8eI1vtEa9YJ/18MGYc+Yv2vFsnLasKNGIYmNTP73VlCXf/9R3zQE0sY850JcvDDJtHIM/PTVmIqaeILFgyvo6zJefjbKTaDp2S2yj+91gNgWhyahRMLshu1nQmUcbyvtnza2Jkh6SuFPQbST68LOUF874FUoLVA0uJtzxXWW++5NCoqE8/RbFVALCNE3BlDDjCYHJ68rnQEslU1u8hsdiPB9HkARWhrvOCRvdhPlRrunN4BC/jbnAdiNat9Pe9DoVkoPd8j7+gmjokgN8GH+I8NT9BOdcCKlG6vk/Dt6Yxxz9m3Rf918pDlm4/DK8UoXDCRbXyBjq++KjoFU6UpUOsONxGsV23deglFQeWxDZqBJ8w/Xh1hp5k2yo3CX+oXAREI021E+ogWx5+ismwg1pLDehhsyNkpcJidEwLF/OfI2/H3uGrzJhcYiV6YEFLhW3GTsKjyW8z4SqLttd/dIP8hTyxQmhG/KKO6CnciL5w==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops
  namespace: default
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/mpaygude-mgmt
      fluxSystemNamespace: flux-system
      owner: mitalipaygude
      personal: true
      repository: gitops-tink

---
