apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-1
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium:
        policyEnforcementMode: default
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.80.8.29
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt-cp
  datacenterRef:
    kind: TinkerbellDatacenterConfig
    name: mpaygude-mgmt
  gitOpsRef:
    kind: GitOpsConfig
    name: gitops
  kubernetesVersion: "1.24"
  managementCluster:
    name: mpaygude-mgmt
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: TinkerbellMachineConfig
      name: mpaygude-mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellDatacenterConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  tinkerbellIP: 10.80.8.50

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: mpaygude-mgmt-cp
  namespace: default
spec:
  hardwareSelector:
    type: cp
  osFamily: bottlerocket
  templateRef: {}
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2r/qQkRnpCUNLEAwReoueGWR/pIQ8dfmNJjVH38LLwSfcCyKGZ/pg6MawB+qwOFNeEAJNe17iHTItyqHlCFaCFAhX96y3jTxmETAqUSS0gSSg/HVWsmlSRq8OQj3UHuLuVHjstLP4v2KS+GOZlEmvF7AotSyjRIWNWD55RorIuddMyOWOks5ODoD0uZcoNsb6Vb5GqklhTmN09Ou7Kl5sMMlCgq5xu9VJUwIVUT8rPQ3onLi+UiExjj7txg9mnu5MrvQNL/XxDzWbaFkfLVsS4UdG25Y1ycF0vOD4pVtsuHkO3IOKsCV46W6JVGuIH4vjMq4qE3gU8zU6mJCw1nb5MWojT3+z+lDpG3LBcRYrgLaC6+JZmlGvJVH6mERThuAuRs69jt/rI5nILGUBgAdh+AMpV+FRqR4Wu4XN1Mcccm8L2yhCoLCmc4eonfvnBfg4h3B/H+VhEKUGY5hWJDxFmrUgKuGdnGHiRUFWCETRuJySAa21yA6ydDwtihdfcFDe9zxZt5Gj+TbeqkkyCWJQblSUOfG5pMaKgzUBSG7LOc0CjCWHg9/affzyBptswYdHlOSBzyQQQcWdZRNdOcnta0HR+VxdDcsXtme2dT6cqTntp12YbEy0q0zQ1+brPKqDlQign07M84feQmNJsdsn6bFcg2pV3DgT0Ejsap25vw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: TinkerbellMachineConfig
metadata:
  name: mpaygude-mgmt
  namespace: default
spec:
  hardwareSelector:
    type: worker
  osFamily: bottlerocket
  templateRef: {}
  users:
  - name: capv
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2r/qQkRnpCUNLEAwReoueGWR/pIQ8dfmNJjVH38LLwSfcCyKGZ/pg6MawB+qwOFNeEAJNe17iHTItyqHlCFaCFAhX96y3jTxmETAqUSS0gSSg/HVWsmlSRq8OQj3UHuLuVHjstLP4v2KS+GOZlEmvF7AotSyjRIWNWD55RorIuddMyOWOks5ODoD0uZcoNsb6Vb5GqklhTmN09Ou7Kl5sMMlCgq5xu9VJUwIVUT8rPQ3onLi+UiExjj7txg9mnu5MrvQNL/XxDzWbaFkfLVsS4UdG25Y1ycF0vOD4pVtsuHkO3IOKsCV46W6JVGuIH4vjMq4qE3gU8zU6mJCw1nb5MWojT3+z+lDpG3LBcRYrgLaC6+JZmlGvJVH6mERThuAuRs69jt/rI5nILGUBgAdh+AMpV+FRqR4Wu4XN1Mcccm8L2yhCoLCmc4eonfvnBfg4h3B/H+VhEKUGY5hWJDxFmrUgKuGdnGHiRUFWCETRuJySAa21yA6ydDwtihdfcFDe9zxZt5Gj+TbeqkkyCWJQblSUOfG5pMaKgzUBSG7LOc0CjCWHg9/affzyBptswYdHlOSBzyQQQcWdZRNdOcnta0HR+VxdDcsXtme2dT6cqTntp12YbEy0q0zQ1+brPKqDlQign07M84feQmNJsdsn6bFcg2pV3DgT0Ejsap25vw==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops
  namespace: default
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/mpaygude-mgmt
      fluxSystemNamespace: flux-system
      owner: mitalipaygude
      personal: true
      repository: gitops-tink

---
